#eureka client 单节点配置
server:
  port: 9200
spring:
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1
  sleuth:
    sampler:
      rate: 1
  application:
    name: spring-cloud-consumer
eureka:
  client:
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
    #默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    serviceUrl.defaultZone: http://localhost:8000/eureka/
#feign:
#  hystrix:
#    enabled: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: 'hystrix.stream'



management:
  endpoints:
    web:
      exposure:
        #yml加双引号，properties不用加
        include: "*"
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true