#eureka client 单节点配置
server:
  port: 9100
spring:
  application:
    name: spring-cloud-zuul
eureka:
  client:
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
    #默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    serviceUrl.defaultZone: http://localhost:8000/eureka/
#修改负载均衡策略
spring-cloud-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  #是否开启重试功能
zuul:
  retryable: true
  #对当前服务的重试次数
ribbon:
  MaxAutoRetries: 2
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 0

#feign:
#  hystrix:
#    enabled: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: 'hystrix.stream'
